# Site settings
title: Brian Bugh
email: contact@brianbugh.me
description: > # this means to ignore newlines until "baseurl:"
  Brian Bugh is a Systems Engineer with sixteen years of professional
  programming experience in web and games, specialized in building the
  foundation for platforms and teams, robust designs, and inspiring
  leadership.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://brianbugh.me" # the base hostname & protocol for your site
twitter_username: brainbag
github_username:  bbugh

# Build settings
markdown: kramdown
